// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: habits-query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, title, completed, created_at, updated_at FROM habits
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHabit(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
