// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Habit struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
